Algoritmo "100sequenciais"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/12/2021
Var
s: vetor[1..5] de inteiro
cont: inteiro
     veta, vetb, vetr: inteiro

 Inicio

 x <- 0
     para x de 1 ate 5 passo 1 faca
     leia (veta[x], vetb[x];
     vetr[x] <- veta[x] + vetb[x]
     escreva (vetr[x])
     


Fimalgoritmo