Algoritmo "TestandoVetores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Francisco Paulo Abreu Alves
// Data atual  : 21/11/2021
Var
v:  vetor[1..4] de inteiro
c: inteiro

Inicio

para c <-1 ate 4 faca
       Escreva("Digite o ", c, "o. valor: ")
       leia(v[c])
fimpara

para c <-1 ate 4 faca
       escreva("{",v[c], "}")
fimpara

Fimalgoritmo